### PR TITLE
Fix/direct indirect hurdles cost

### LINKED ISSUE #182: Bug when hurdle costs are activated on candidate link
The problem is related to additional constraints added in Antares when there are hurdle costs on the candidate link.

•	Indeed, if the "Use hurdles cost" button is green, those additional constraints  appear in Antares (even if hurdle costs are set to zero …).
image

To detail a little more mathematically, p[t] is the flow on the candidate link and Pmax is the capacity of the link. 
Here are the constraints that are in Antares :

-       p[t] reprensents the flow on the link

- 	–pMax_indirect <= p[t] <= pMax_direct, --> Xpansion changes this Pmax value with each iteration, taking into account already_installed_capacity and new investments

- 	 p[t]=p+[t] - p-[t] and p+[t]≤pMax_direct and p-[t]≤pMax_indirect , --> those  last constraints appear only when there are hurdle costs and Xpansion has not updated them with the right Pmax, this is a bug that needs to be fixed. Those constraints take into account the Pmax capacities that are in the Antares interface instead of taking the capacities of Xpansion, which can limit the Xpansion solution. In order not to affect the optimization and avoid the bug, you do as you did: put a large non-limiting capacity (e.g. 10000 MW, and use an already_installed_capacity in the candidate.ini file if you want, as you did), and you can also put positive hurdle costs if you want. This is a quick fix until we fix the tool.

Name of variables  p+ et p- in Antares :

CoutOrigineVersExtremiteDeLInterconnexion
CoutExtremiteVersOrigineDeLInterconnexion

Modification of MPS problem file for each hour (here hour = 141) of the week :
 UP BOUND                                             CoutOrigineVersExtremiteDeLInterconnexion_0_141_       2000.01
 UP BOUND                                             CoutExtremiteVersOrigineDeLInterconnexion_0_141_       2000.01

--> becomes :
 UP BOUND                                             CoutOrigineVersExtremiteDeLInterconnexion_0_141_       Xpansion_capacity_variable
 UP BOUND                                             CoutExtremiteVersOrigineDeLInterconnexion_0_141_       Xpansion_capacity_variable

### PR DESCRIPTION
**Pull request by jmkerloch**
closes #182

### CODE REVIEW

File: tests/cpp/lp_namer/ProblemModifierTest.cpp [hunk 1]
```diff
@@ -319,121 +355,159 @@ TEST_F(ProblemModifierTest, One_link_two_candidates_two_timestep) {
...
+    math_problem = problem_modifier.changeProblem(std::move(math_problem), links, p_var_columns,p_direct_cost_columns,p_indirect_cost_columns);
+    verify_columns_are(5);
+
+    const int P_LINK_id  = 0;
+    const int P_PLUS_id = 1;
+    const int P_MINUS_id = 2;
+    const int cand1_id= 3;
+    const int cand2_id= 4;
+
+    verify_column(P_LINK_id,P_LINK,'C',1,-1e20,1e20);
```
Comment (sgatto) [inline tests/cpp/lp_namer/ProblemModifierTest.cpp:367]: we can "rename"
`0` into `ZERO` 
`1e20` into `PLUS_INF` 
`-1e20` into `MINUS_INF` 

the third argument, if I remember well corresponds to the  variable type
1=double (or continuous)
0=integer

we could name two constants:
`INTEGER_VAR`
`CONTINUOUS_VAR`
 Continuous or other, I dontremeber how the multisolver interface colls it

**Review by sgatto — CHANGES_REQUESTED** [review]
only one small observation? not mandatory

File: tests/cpp/lp_namer/ProblemModifierTest.cpp (hunk 1 above)
Comment (jmkerloch) [reply tests/cpp/lp_namer/ProblemModifierTest.cpp]: third argument is objective. No new constant defined

**Review by sgatto — APPROVED** [review]
