### PR TITLE
Fix/ortools mps rounding

### LINKED ISSUE #89: Rounding problem in writing MPS with ORTOOLS -  ERROR: exited solver with status 1 - lp_status is : 2 ORT_INFEASIBLE
In the following study example :
[
[xpansion-test-01-bug-ORTOOLS.zip](https://github.com/AntaresSimulatorTeam/antares-xpansion/files/6182018/xpansion-test-01-bug-ORTOOLS.zip)

](url)
There is a rather tight Antares constraint in the Hydro storage of  "area1".
**ORTOOLS rounds the data** of this hydraulic constraint in the writing of the MPS.
--> This makes this constraint unfeasible and creates the following error in Xpansion: 
"ERROR: exited solver with status 1"
"lp_status is : 2"
"lp_status is : ORT_INFEASIBLE"
"written in .\problem-1-47-20210322-120403.mps_lp_status_ORT_INFEASIBLE.mps"

Solution :
1) First, try to change the precision in the MPS writing if it is possible directly with ORTOOLS.
2) Otherwise, we need to talk about it again. One solution is to send the problems to the solver and ask the solver to write the MPS (done formerly by Manuel with Xpress), this assumes that the solvers (CLP/CBC?) have a "write MPS" function.

### PR DESCRIPTION
**Pull request by jmkerloch**
Integration of @Blaxav work for MPS write with CLP use.

closes #89 

absolute tolerance is now 0.1 for investments, costs and gap comparison

### CODE REVIEW

**Review by flomnes — COMMENTED** [review]
I suggest the following :
- Absolute tolerance 1e-1 for gap
- Relative tolerance 1e-4 for the rest

File: src/src_cpp/src_helpers/ortools_utils.cc [hunk 1]
```diff
@@ -99,6 +99,121 @@ bool ORTwritemps(operations_research::MPSolver const & solver_p, std::string con
 	return true;
 }
 
+void ORTwritempsPreciseWithCoin(operations_research::MPSolver & solver_p,
```
Comment (sgatto) [inline src/src_cpp/src_helpers/ortools_utils.cc:102]:
```suggestion
void ORTwriteMpsPreciseWithCoin(operations_research::MPSolver & solver_p, 
```

**Review by sgatto — APPROVED** [review]
