### PR TITLE
Update default values and fix docs

### LINKED ISSUE #560: Choose good default values for in-out stabilization
Default values of the parameters `separation_parameter`and  `relaxed_optimality_gap` should be tuned so that the in-out stabilization is efficient. The docs should be updated as well.

### PR DESCRIPTION
**Pull request by tbittar**
Closes #560

### CODE REVIEW

File: src/cpp/benders/benders_core/BendersBase.cpp [hunk 1]
```diff
@@ -525,16 +526,10 @@ LogData BendersBase::build_log_data_from_data() const {
 LogData BendersBase::FinalLogData() const {
   LogData result;
 
-  result.it = _data.it + iterations_before_resume;
   result.best_it = _data.best_it + iterations_before_resume;
-  result.lb = _data.lb;
-  result.best_ub = _data.best_ub;
-  result.x_out = _data.x_in;
```
Comment (a-zakir) [inline src/cpp/benders/benders_core/BendersBase.cpp:532]: why ?

**Review by a-zakir — APPROVED** [review]

File: src/cpp/benders/benders_core/BendersBase.cpp (hunk 1 above)
Comment (tbittar) [reply src/cpp/benders/benders_core/BendersBase.cpp:532]: Data is unused
