### PR TITLE
[ANT-1890] Properly handle playlist_reset in generaldata.ini

### LINKED ISSUE #864: [1.3.0] stoi error parsing playlist
In GeneralDataReader.h:GetKeyValFromLine
We parse the section "[playlist]" of generalData.ini

If most values are in the form of "key += Number" one valid entry is "playlist_reset = False"
We use "std::stoi" to convert numbers, however "False" is not a valid representation of a number.

Historically we used std::atoi which does not throw and return 0 in case of error.

std::atoi is useful for playlist_reset entry, but if we have an invalid "key += Number" entry it will silently fail and wrongly set 0 as value for the key.

I think we should handle the exception properly in case Number is invalid and generate meaningful error.
We could however ignore "playlist_reset" line entirely either inside GetKeyValFromLine and return {"", 0} or not call GetKeyValFromLine for playlist_reset line.

Fix should be applied to 1.3.0 release. Check 1.2.x version if bug is present too.

### PR DESCRIPTION
**Pull request by JasonMarechal25**
Fix #864 
Properly handle data and avoid exception thrown when reading not numerical values with stoi when reading "playlist_reset" entry in general_data.ini

### CODE REVIEW

**Review by a-zakir — DISMISSED** [review]

File: src/cpp/lpnamer/input_reader/GeneralDataReader.cpp [hunk 1]
```diff
@@ -1,8 +1,37 @@
...
+  static std::string ReadSectionHeader(const std::string& line) {
+    auto str = StringManip::trim(line);
+    str.erase(std::remove(str.begin(), str.end(), '['), str.end());
+    str.erase(std::remove(str.begin(), str.end(), ']'), str.end());
+    return str;
+  }
+
+  static std::pair<std::string, int> GetKeyValFromLine(std::string_view line) {
+    auto key = StringManip::trim(StringManip::split(line, '=')[0]);
+    auto val = std::stoi(StringManip::trim(StringManip::split(line, '=')[1]));
```
Comment (flomnes) [inline src/cpp/lpnamer/input_reader/GeneralDataReader.cpp]:
```suggestion
    const auto splitLine = StringManip::split(line, '=');
    auto key = StringManip::trim(splitLine[0]);
    auto val = std::stoi(StringManip::trim(splitLine[1]));
```

File: tests/cpp/lp_namer/GeneralDataReadetTests.cpp [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+  auto test_dir = std::filesystem::temp_directory_path() / std::tmpnam(nullptr);
+  std::filesystem::create_directory(test_dir);
+  auto ini_file = test_dir / "test.ini";
+  std::ofstream file(ini_file);
+  file << "[general]\n"
+          "nbyears=10\n"
+          "user-playlist=true\n"
+          "[playlist]\n"
+          "playlist_reset = ";
+  GetParam() ? file << "true\n" : file << "false\n";
```
Comment (flomnes) [inline tests/cpp/lp_namer/GeneralDataReadetTests.cpp]:
```suggestion
  file << (GetParam() ? "true\n" : "false\n");
```

**Review by flomnes — APPROVED** [review]
